---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/camwp
          icon: https://cdn-icons-png.flaticon.com/512/25/25231.png
- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/Sundaii20
          icon: https://www.redditstatic.com/shreddit/assets/favicon/64x64.png

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/PurpleRabbitGrabber
          icon:  https://www.youtube.com/s/desktop/4981804c/img/logos/favicon.ico
